In [1]:
import sys
import os
sys.path.append(os.path.abspath('../src'))

In [2]:
import sys
import os
sys.path.append(os.path.abspath('../src'))

from src.loadData import load_data

df = load_data("../data/taxi_data.csv")

ModuleNotFoundError: No module named 'src'

In [4]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,1,2016-03-01 00:00:00,2016-03-01 00:07:55,1,2.50,-73.976746,40.765152,1,N,-74.004265,40.746128,1,9.0,0.5,0.5,2.05,0.00,0.3,12.35
1,1,2016-03-01 00:00:00,2016-03-01 00:11:06,1,2.90,-73.983482,40.767925,1,N,-74.005943,40.733166,1,11.0,0.5,0.5,3.05,0.00,0.3,15.35
2,2,2016-03-01 00:00:00,2016-03-01 00:31:06,2,19.98,-73.782021,40.644810,1,N,-73.974541,40.675770,1,54.5,0.5,0.5,8.00,0.00,0.3,63.80
3,2,2016-03-01 00:00:00,2016-03-01 00:00:00,3,10.78,-73.863419,40.769814,1,N,-73.969650,40.757767,1,31.5,0.0,0.5,3.78,5.54,0.3,41.62
4,2,2016-03-01 00:00:00,2016-03-01 00:00:00,5,30.43,-73.971741,40.792183,3,N,-74.177170,40.695053,1,98.0,0.0,0.0,0.00,15.50,0.3,113.80

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 19 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   VendorID               100000 non-null  int64
 1   tpep_pickup_datetime   100000 non-null  str
 2   tpep_dropoff_datetime  100000 non-null  str
 3   passenger_count        100000 non-null  int64
 4   trip_distance          100000 non-null  float64
 5   pickup_longitude       100000 non-null  float64
 6   pickup_latitude        100000 non-null  float64
 7   RatecodeID             100000 non-null  int64
 8   store_and_fwd_flag     100000 non-null  str
 9   dropoff_longitude      100000 non-null  float64
 10  dropoff_latitude       100000 non-null  float64
 11  payment_type           100000 non-null  int64
 12  fare_amount            100000 non-null  float64
 13  extra                  100000 non-null  float64
 14  mta_tax                100000 non-null  float64
 15  tip_amount             100000 non-null  float64
 16  tolls_amount           100000 non-null  float64
 17  improvement_surcharge  100000 non-null  float64
 18  total_amount           100000 non-null  float64
dtypes: float64(12), int64(4), str(3)
memory usage: 14.5 MB

In [6]:
# Datetime transformation
df['tpep_pickup_datetime'] = pd.to_datetime(df['tpep_pickup_datetime'])
df['tpep_dropoff_datetime'] = pd.to_datetime(df['tpep_dropoff_datetime'])

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 19 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   VendorID               100000 non-null  int64
 1   tpep_pickup_datetime   100000 non-null  datetime64[us]
 2   tpep_dropoff_datetime  100000 non-null  datetime64[us]
 3   passenger_count        100000 non-null  int64
 4   trip_distance          100000 non-null  float64
 5   pickup_longitude       100000 non-null  float64
 6   pickup_latitude        100000 non-null  float64
 7   RatecodeID             100000 non-null  int64
 8   store_and_fwd_flag     100000 non-null  str
 9   dropoff_longitude      100000 non-null  float64
 10  dropoff_latitude       100000 non-null  float64
 11  payment_type           100000 non-null  int64
 12  fare_amount            100000 non-null  float64
 13  extra                  100000 non-null  float64
 14  mta_tax                100000 non-null  float64
 15  tip_amount             100000 non-null  float64
 16  tolls_amount           100000 non-null  float64
 17  improvement_surcharge  100000 non-null  float64
 18  total_amount           100000 non-null  float64
dtypes: datetime64[us](2), float64(12), int64(4), str(1)
memory usage: 14.5 MB

In [8]:
# (1) dim_datetime Construction
dim_datetime = df[['tpep_pickup_datetime', 'tpep_dropoff_datetime']].drop_duplicates().reset_index(drop=True)

# pickup
dim_datetime['pick_hour'] = dim_datetime['tpep_pickup_datetime'].dt.hour
dim_datetime['pick_day'] = dim_datetime['tpep_pickup_datetime'].dt.day
dim_datetime['pick_month'] = dim_datetime['tpep_pickup_datetime'].dt.month
dim_datetime['pick_year'] = dim_datetime['tpep_pickup_datetime'].dt.year
dim_datetime['pick_weekday'] = dim_datetime['tpep_pickup_datetime'].dt.weekday

# drop-off
dim_datetime['drop_hour'] = dim_datetime['tpep_dropoff_datetime'].dt.hour
dim_datetime['drop_day'] = dim_datetime['tpep_dropoff_datetime'].dt.day
dim_datetime['drop_month'] = dim_datetime['tpep_dropoff_datetime'].dt.month
dim_datetime['drop_year'] = dim_datetime['tpep_dropoff_datetime'].dt.year
dim_datetime['drop_weekday'] = dim_datetime['tpep_dropoff_datetime'].dt.weekday

# datetim_id
dim_datetime['datetime_id'] = dim_datetime.index

# Remove duplicates
dim_datetime = dim_datetime[['datetime_id', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
                            'pick_hour', 'pick_day', 'pick_month', 'pick_year', 'pick_weekday', 
                            'drop_hour', 'drop_day', 'drop_month', 'drop_year', 'drop_weekday']].drop_duplicates().reset_index(drop=True)
dim_datetime.head()

,datetime_id,tpep_pickup_datetime,tpep_dropoff_datetime,pick_hour,pick_day,pick_month,pick_year,pick_weekday,drop_hour,drop_day,drop_month,drop_year,drop_weekday
0,0,2016-03-01 00:00:00,2016-03-01 00:07:55,0,1,3,2016,1,0,1,3,2016,1
1,1,2016-03-01 00:00:00,2016-03-01 00:11:06,0,1,3,2016,1,0,1,3,2016,1
2,2,2016-03-01 00:00:00,2016-03-01 00:31:06,0,1,3,2016,1,0,1,3,2016,1
3,3,2016-03-01 00:00:00,2016-03-01 00:00:00,0,1,3,2016,1,0,1,3,2016,1
4,4,2016-03-01 00:00:01,2016-03-01 00:16:04,0,1,3,2016,1,0,1,3,2016,1

In [9]:
# (2) dim_passenger_count Construction
dim_passenger_count = df[['passenger_count']].drop_duplicates().reset_index(drop=True)
dim_passenger_count['passenger_count_id'] = dim_passenger_count.index

dim_passenger_count = dim_passenger_count[['passenger_count_id','passenger_count']]

# (3) dim_trip_distance Construction
dim_trip_distance = df[['trip_distance']].drop_duplicates().reset_index(drop=True)
dim_trip_distance['trip_distance_id'] = dim_trip_distance.index

dim_trip_distance = dim_trip_distance[['trip_distance_id', 'trip_distance']]

In [10]:
dim_passenger_count.head()

   passenger_count_id  passenger_count
0                   0                1
1                   1                2
2                   2                3
3                   3                5
4                   4                6

In [11]:
dim_trip_distance.head()

   trip_distance_id  trip_distance
0                 0           2.50
1                 1           2.90
2                 2          19.98
3                 3          10.78
4                 4          30.43

In [12]:
# (4) dim_rate_code Construction

# On data/DataSource_description.pdf i can see how the names of each RatecodeID is declared. 
# Hasmap declaration:
rate_code_type = {
    1 : "Standard rate",
    2 : "JFK",
    3 : "Newark",
    4 : "Nassau or Westchester",
    5 : "Negotiated fare",
    6 : "Group ride",
    99: "Null/unknown"
}

dim_rate_code = df[['RatecodeID']].drop_duplicates().reset_index(drop=True)
dim_rate_code['ratecode_id'] = dim_rate_code.index
dim_rate_code['ratecode_name'] = dim_rate_code['RatecodeID'].map(rate_code_type)

dim_rate_code = dim_rate_code[['ratecode_id', 'RatecodeID', 'ratecode_name']]

In [13]:
dim_rate_code.head()

   ratecode_id  RatecodeID          ratecode_name
0            0           1          Standard rate
1            1           3                 Newark
2            2           2                    JFK
3            3           5        Negotiated fare
4            4           4  Nassau or Westchester

In [14]:
# (5) dim_pickup_location Construction
dim_pickup_location = df[['pickup_longitude', 'pickup_latitude']].drop_duplicates().reset_index(drop=True)
dim_pickup_location['pickup_id'] = dim_pickup_location.index
dim_pickup_location = dim_pickup_location[['pickup_id', 'pickup_latitude', 'pickup_longitude']]

# (6) dim_dropoff_location Construction
dim_dropoff_location = df[['dropoff_longitude', 'dropoff_latitude']].drop_duplicates().reset_index(drop=True)
dim_dropoff_location['dropoff_id'] = dim_dropoff_location.index
dim_dropoff_location = dim_dropoff_location[['dropoff_id', 'dropoff_latitude', 'dropoff_longitude']]

In [15]:
dim_pickup_location.head()

   pickup_id  pickup_latitude  pickup_longitude
0          0        40.765152        -73.976746
1          1        40.767925        -73.983482
2          2        40.644810        -73.782021
3          3        40.769814        -73.863419
4          4        40.792183        -73.971741

In [16]:
dim_dropoff_location.head()

   dropoff_id  dropoff_latitude  dropoff_longitude
0           0         40.746128         -74.004265
1           1         40.733166         -74.005943
2           2         40.675770         -73.974541
3           3         40.757767         -73.969650
4           4         40.695053         -74.177170

In [17]:
# (7) dim_payment_type Construction
# On data/DataSource_description.pdf i can see how the names of each payment type is declared. 
# Hasmap declaration:
payment_type = {
    0 : "Flex Fare trip",
    1 : "Credit card",
    2 : "Cash",
    3 : "No charge",
    4 : "Dispute",
    5 : "Unknown",
    6 : "Voided trip"
}

dim_payment_type = df[['payment_type']].drop_duplicates().reset_index(drop=True)
dim_payment_type['payment_type_id'] = dim_payment_type.index
dim_payment_type['payment_type_name'] = dim_payment_type['payment_type'].map(payment_type)

dim_payment_type = dim_payment_type[['payment_type_id', 'payment_type', 'payment_type_name']]

In [18]:
dim_payment_type.head()

   payment_type_id  payment_type payment_type_name
0                0             1       Credit card
1                1             2              Cash
2                2             3         No charge
3                3             4           Dispute

In [19]:
# (8) fact_table Construction
fact_table = df.merge(dim_datetime, on=['tpep_pickup_datetime', 'tpep_dropoff_datetime']) \
             .merge(dim_passenger_count, on='passenger_count') \
             .merge(dim_trip_distance, on='trip_distance') \
             .merge(dim_pickup_location, on=['pickup_longitude', 'pickup_latitude']) \
             .merge(dim_dropoff_location, on=['dropoff_longitude', 'dropoff_latitude']) \
             .merge(dim_rate_code, on='RatecodeID') \
             .merge(dim_payment_type, on='payment_type') \
             [[
                 'VendorID',
                 'datetime_id',
                 'passenger_count_id',
                 'trip_distance_id',
                 'pickup_id',
                 'dropoff_id',
                 'ratecode_id',
                 'payment_type_id',
                 'fare_amount',
                 'extra',
                 'mta_tax',
                 'tip_amount',
                 'tolls_amount',
                 'improvement_surcharge',
                 'total_amount'
             ]]